### ISSUE TITLE
Starting instructions

### ISSUE THREAD

**Issue by shirakaba** [cbrevik/react-native-typescript-starter#8]
Thanks for the recent dependencies update!

As I said, I believe I had this working last night, but I'm rather new to all this, and it is a starter project after all – when developing for iOS, what are the first commands I should run?

I've done:

```
yarn install
yarn run start
```

This of course installs the dependencies and runs the Metro Bundler. Somehow I have an app on my iOS Simulator called 'typescriptStarter', and I recall having to run a command to first build it, which took a very long time, but I can't find that command in my terminal history anywhere. I'm rather afraid to break anything, however. **How can I build (and run) this project in the iOS simulator?**

Is the command something like `react-native-scripts ios` (as used by [create-react-native-app](https://github.com/react-community/create-react-native-app), under the alias `npm run ios`)? If so, it would be worth adding that alias into this project's `package.json` to help first-time starters. Equally, any other first-time setup instructions into the `readme.md`.

**Comment by shirakaba** [comment]
Found the command again, via [Saket Sinha's article](https://medium.com/@saketsinha23/reactnative-starter-with-typescript-4af9527e9142): `react-native run-ios` (or equally `react-native run-android`). Sorry for the bother!

**Comment by shirakaba** [comment]
Actually, I'm still going to need some guidance. `react-native run-ios` certainly built an app in the iOS Simulator, but the app still throws errors on startup.

First, it was complaining about a lack of a `index.ios.js` file, so I duplicated the existing `index.js` and renamed it to `index.ios.js`, which got it past that error. However, now it's saying "No bundle URL present. Make sure you're running a packager server or have included a `.jsbundle` file in your application bundle.".

What's the recommended startup process for developing on iOS using this project?

**Comment by shirakaba** [comment]
Okay, I got it to work, at long last. No clever steps; just a lot of repeating exactly the same thing:

Ideal process to clone the repo, build the app for the iOS simulator, and run it alongside the packager:

- `git clone` the repository and `cd` into it.
- `yarn install`
- Duplicate the `index.js` file at the repository root, and rename the duplicate as `index.ios.js`. This step may not be necessary, but... whatever works.
- Ensure that you have no other packagers running on port 8081 (`sudo lsof -i :8081` should return empty; otherwise, run `kill -9 <relevant pid>` on all returned pids, again running `sudo lsof -i :8081` after each kill to see whether all the processes have yet been killed).
- `react-native run-ios`

If, at this point, you can see an error on the iPhone simulator start screen, follow these steps to stop the packager running, and rebuild the app:

- `sudo lsof -i :8081` and `kill -9 <relevant pid>`, as described before.
- Delete the `ios/build` folder.
- Optionally delete the `node_modules` folder.
- Optionally open a new terminal (during `react-native run-ios`, my terminal was alarmingly following symlinks into my Trash; this was probably due to failing to kill the packager process before proceeding to the next steps)
- Optionally empty your Trash, as you've just deleted some big folders.

The app should run, and look like this:

<img width="194" alt="screen shot 2018-03-09 at 19 29 33" src="https://user-images.githubusercontent.com/14055146/37225967-52188d20-23d0-11e8-8271-39a604d8f41e.png">

**Comment by cbrevik** [comment]
Nice @shirakaba. I was just about to comment that I think this is a bit outside of the scope of this repository. There's no specific startup-instructions for TS other than what is normal RN commands. (That's sort of the point with the blog post)

`react-native run-ios` would be the command to use, after installing dependencies (with `yarn`).
I'd recommend getting to know React Native, and the CLI-tool (`react-native --help`), better. Sometimes the problem can be caching, or the RN bundle packager is not running. You can start the packager with `react-native start`. Include `--reset-cache` if you think there's a caching issue.

Sometimes re-building/cleaning the native app can help. But as I said, recommend getting to know RN better first :)

Happy it worked out in the end though!

**Comment by shirakaba** [comment]
> I'd recommend getting to know React Native, and the CLI-tool (react-native --help), better.

Working on it! I did get a non-TypeScript project running before this and had a fiddle with it, but I feel that I can really go at full power if I can get TypeScript at my side, however.

Would you say that the suggested method of usage is: Rather than adapting from this repo, to build one's React app through the usual `create-react-native-app` routine, then, following your [blog post](http://blog.novanet.no/easy-typescript-with-react-native/)'s instructions, adopt TypeScript into it? Just that I've had difficulties renaming the package to something else, so it seems like I've missed the point here.

Thanks for the hints. Is `react-native start` just an alias for `node node_modules/react-native/local-cli/cli.js start`?

**Comment by cbrevik** [comment]
Using `create-react-native-app` is in turn using Expo as far as I know. So I sort of doubt the instructions are the same. I don't really use Expo myself. But I see an issue about it here: https://github.com/expo/expo/issues/428

This repository is an example on how to do it with "full framework" React Native.  In other words, projects created with `react-native init` instead of `create-react-native-app`.

See the "Building Projects with Native Code"-tab in the getting started guide for more info on non-Expo React Native: http://facebook.github.io/react-native/docs/getting-started.html

**Comment by cbrevik** [comment]
> Is react-native start just an alias for node node_modules/react-native/local-cli/cli.js start?

Pretty much. But as I said, if you're using Expo, then you might have to use other CLI commands.
