### ISSUE TITLE
Property 'counter' does not exist on type '{}'.

### ISSUE THREAD

**Issue by matthewcarlreetz** [cbrevik/react-native-typescript-starter#9]
Getting this error in Counter.tsx `Property 'counter' does not exist on type '{}'.`
<img width="458" alt="screen shot 2018-03-16 at 9 59 43 pm" src="https://user-images.githubusercontent.com/1760821/37550988-6b52739c-2965-11e8-8d75-5e369475da2e.png">

**Comment by cbrevik** [comment]
Fixed this, as well as added a precommit hook to check for stuff like this 😬
